### ISSUE TITLE
Rassine.py redefines "column_wave" and "column_wave" after reading Rassine_config.py to fixed values

### ISSUE THREAD

**Issue by ronnyerrmann** [MichaelCretignier/Rassine_public#1]
**Describe the bug**
Rassine.py redefines "column_wave" and "column_wave" after reading Rassine_config.py to fixed values

**To Reproduce**
1. Rassine.py line 58 and 59 read from Rassine_config.py: column_wave = config['column_wave'] ; column_flux = config['column_flux']
2. Rassine.py line 99 and 100 reverts to standard values: column_wave = 'wave' ; column_flux = 'flux'
3. This creates an error, if the data is not labeled in standard values in line 199: spectrei = np.array(data[column_flux])

**Expected behavior**
A parameter changed in the config should not be overwritten

**Additional context**
Rassine was pulled on 11 Jan 2021

**Comment by MichaelCretignier** [comment]
Thank you, 
 
Indeed the name for the columns were hardcoded in the main code. I changed it and now the correct name from Rassine_config.py file is taken.
