### ISSUE TITLE
Rassine.py does not run if 5500 A not present in spectrum

### ISSUE THREAD

**Issue by SaptarshiSrkr** [MichaelCretignier/Rassine_public#4]
Rassine.py checks the SNR value by looking at wavelengths near 5500 A, but the spectrums of very low mass stars typically start from 6500 A. It throws an error in such cases.

Adding a parameter to select the central wavelength for noise calculation may make the tool more useful for these types of cases.

**Comment by MichaelCretignier** [comment]
Hi, 

I added a condition to check if 5500AA was inside the wavelength range, if not the new wavelength reference is set to to mean of the wavelength range. 

Note that I didn't change the keyword in the output file (SNR_5500) to avoid breaking code of other people that may have implemented their own routines already.

**Comment by SaptarshiSrkr** [comment]
Thanks!
